### ISSUE TITLE
update app icon to the new style

### ISSUE THREAD

**Issue by jimmac** [myfreeweb/galacritty#1]
We have a new [style revolution going on in GNOME](https://developer.gnome.org/hig/stable/icon-design.html.en). I randomly stumbled across you app and felt like making an app icon for you.

I would have submitted a merge request, but github forking is broken right now ;)

**Comment by jimmac** [comment]
http://jimmac.musichall.cz/stuff/0001-update-app-icon.patch

**Comment by valpackett** [comment]
Wow!! That was an unexpected surprise, thanks a lot!!

Honestly, I still kinda like the old style more than following the flat design trend, but if GNOME goes there, I don't want to be left out :D And dropping the PNGs is great.
